name: Test Ntfy Workflow

on:
  workflow_dispatch:

jobs:
  test-notification:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Récupération du code
        uses: actions/checkout@v4

      - name: ⬡ Installation de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 📦 Installation des dépendances (axios)
        run: npm install axios

      - name: 🚀 Lancement du test de notification
        env:
          NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}
        run: node test-ntfy.js
