name: Pokemon TCG Scraper

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Récupération du code
        uses: actions/checkout@v4

      - name: ⚙️ Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 📦 Installation des dépendances
        run: npm install playwright cheerio dotenv

      - name: 🎭 Installation des navigateurs Playwright
        run: npx playwright install --with-deps chromium

      - name: 🚀 Lancement du Scraper
        run: node src/index.js
        env:
          NTFY_TOPIC_30ANS: ${{ secrets.NTFY_TOPIC_30ANS }}
          NTFY_TOPIC_ETB: ${{ secrets.NTFY_TOPIC_ETB }}
          NTFY_TOPIC_COFFRET: ${{ secrets.NTFY_TOPIC_COFFRET }}
          NTFY_TOPIC_BUNDLE_BLISTER: ${{ secrets.NTFY_TOPIC_BUNDLE_BLISTER }}
          NTFY_TOPIC_CARTE: ${{ secrets.NTFY_TOPIC_CARTE }}
